FROM registry.access.redhat.com/ubi8/ubi-minimal
RUN microdnf install nc -y
WORKDIR /work/
COPY target/*-runner /work/application
COPY src/main/docker/wait-for-it.sh /work/wait-for-it.sh
RUN chmod 775 /work
CMD ["/work/wait-for-it.sh", "broker:1883", "--", "./application", "-Dquarkus.http.host=0.0.0.0"]
